EMOJIS = {
    "play": "▶️",
    "pause": "⏸️",
    "resume": "⏯️",
    "stop": "⏹️",
    "skip": "⏭️",
    "previous": "⏮️",
    "autoplay": "♾️",
    "music_filter": "🎛️",
    "lofi": "☕",
    "vc247": "⏰",
    "playlist": "📜",
    "volume_high": "🔊",
    "volume_low": "🔉",
    "volume_mute": "🔇",
    "shuffle": "🔀",
    "loop": "🔁",
    "loop_one": "🔂",
    "lyrics": "🎤",
    "queue": "🎶",
    "music_note": "🎵",
    "added_track": "➕",
    "now_playing": "📻"
}
