EMOJIS = {
    'boobs': '🔞',
    'ass': '🍑',
    'pussy': '🔞',
    'hentai': '🔞',
    'cum': '🔞',
    'blowjob': '🔞',
    'sex': '🔞',
    'fuck': '🔞',
    'ero': '🔞',
    'yaoi': '👨‍❤️‍💋‍👨',
    'yuri': '👩‍❤️‍💋‍👩',
    'bdsm': '🔞',
    'tentacle': '🔞',
    'waifu': '👗',
    'neko': '🐱',
    'trap': '🔞',
    'anal': '🔞',
    'lesbian': '👩‍❤️‍💋‍👩',
    'solo': '👤',
    'spank': '🔞',
    'tits': '🍒',
    'threesome': '🔞'
}
